Ape/eme 273 design review
EME-Studio/eme-studio-v2 pull request #10
Opened 2023-04-25 15:45 UTC by falcojuanpedro

Updated orbits position, EME logo, form button and Our services alignment

2023-04-25 20:16 UTC, mateoroldos requested changes
Very good progress! 
Some comments and improvement ideas..

2023-04-25 20:16 UTC, mateoroldos commented on src/lib/components/Orbits.svelte
> +  }
line break!

2023-04-25 20:16 UTC, mateoroldos commented on src/routes/catalog/[project]/+page.svelte
> +    <img src={data.videolink} alt="example" class="image" />
Es esta clase necesaria??

2023-04-25 20:16 UTC, mateoroldos commented on src/lib/styles/components/_images.scss
> +  width: 100%;
Ojo aca..
Seguro queres que TODAS las imagenes tengan borde redondeado y width 100%?

Si este estilo lo queres para una imagen en particular, ponesela a esa imagen adentro de su componente.

Si es un patron que se repite seguido y queres hacerlo reciclable, en vez de aplicarlo a todas las imagenes create una clase.

Se me ocurre algo como `img.full-rounded`

2023-05-02 14:28 UTC, falcojuanpedro commented
Forgot to specify in the commit message that I also push an animation in OurServices section

2023-05-02 20:24 UTC, mateoroldos requested changes
Small code structure improvement

2023-05-02 20:24 UTC, mateoroldos commented on src/lib/components/Video.svelte
> +  video {
Remember to nest classes!

2023-05-03 15:11 UTC, merged