Ape/eme 277 projects page design
EME-Studio/eme-studio-v2 pull request #11
Opened 2023-05-02 14:23 UTC by falcojuanpedro

Created the logic for Projects Page rendering. Comments and ProjectCardInfo components created. Worked in Emerald-Academy markdown file.

2023-05-02 20:47 UTC, mateoroldos requested changes
Some improvements!

2023-05-02 20:47 UTC, mateoroldos commented on src/lib/components/Header.svelte
> +      display: flex;
Este `display: flex` cambia algo?

2023-05-02 20:47 UTC, mateoroldos commented on src/lib/components/individualProjectComponents/Comments.svelte
Careful with naming.. the component renders one Comment, so it should be called `Comment.svelte` instead of `Comments.svelte`

2023-05-02 20:47 UTC, mateoroldos commented on src/lib/components/individualProjectComponents/Comments.svelte
> +        height: 50px;
Also a little suggestion:
If you want this image to maintain the square proportions you can write `aspect-ratio: 1/1`

2023-05-02 20:47 UTC, mateoroldos commented on src/routes/catalog/[project]/+page.ts
> +    const { title, date, excerpt, videolink, tags } = project.metadata;
Aca si te queda mas facil, podes no desestructurar la data (romperla en pedacitos) y mandar todo el project.metadata a la pagina.

Dps en la pagina vas a tener que agregar .metadata antes de acceder a cada una de estos datos.

Esto es si te queda mas comodo, las dos formas funcionan!

2023-05-03 14:45 UTC, falcojuanpedro commented on src/lib/components/individualProjectComponents/ProjectInfoCard.svelte
> +  {#if align}
El tema es que yo esto lo renderizo despues en el markdown y dependiendo del orden la alineacion, me explic?. O sea, en el markdown renderizo mas de una projectinfocard, y ahi quiero cambiarles el orden en caso de que sean mas de una. No se si me explico o capaz no pude con el grid autoflow

2023-05-03 18:36 UTC, mateoroldos commented on src/lib/components/individualProjectComponents/ProjectInfoCard.svelte
> +  {#if align}
Clarisimo!

Ahi podes combinarlo con las conditional classes y queda.

1. Haces una clase que se llame algo como `.invert-grid` que invierta el orden de la grid
2. Agregas una prop booleana que se llame `invert` y por defecto sea `false`
3. A la grid le agregas la clase `.invert-grid` condicionalmente dependeiendo de `invert`: `class:invert-grid={invert}`

2023-05-03 18:39 UTC, mateoroldos reviewed
Todo perfecto!
Solo corregiría el component que hay que invertir la grid y ya mergear 👍

2023-05-04 19:52 UTC, merged